spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

app-properties:
  test-email: user@email.com
  test-password: password
